services:
  # 기본 웹 서버 예제
  basic-server:
    image: nginx:alpine
    container_name: nginx-basic-server
    profiles:
      - basic
      - all
    ports:
      - "8001:80"
    volumes:
      - ./examples/beginner/01-basic-server/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./examples/beginner/01-basic-server/html:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Virtual Hosts 예제
  virtual-hosts:
    image: nginx:alpine
    container_name: nginx-virtual-hosts
    profiles:
      - virtual-hosts
      - all
    ports:
      - "8002:80"
    volumes:
      - ./examples/beginner/02-virtual-hosts/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./examples/beginner/02-virtual-hosts/site1:/var/www/site1:ro
      - ./examples/beginner/02-virtual-hosts/site2:/var/www/site2:ro
      - ./examples/beginner/02-virtual-hosts/wildcard:/var/www/wildcard:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 메인 가이드 페이지 (모든 예제 링크 포함)
  guide:
    image: nginx:alpine
    container_name: nginx-guide
    profiles:
      - guide
      - all
    ports:
      - "8000:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx_config/nginx.conf:/etc/nginx/nginx.conf:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: nginx-guide-network