services:
  nginx:
    image: nginx:alpine
    container_name: virtual-hosts-nginx
    ports:
      - "8002:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./site1:/var/www/site1:ro
      - ./site2:/var/www/site2:ro
      - ./wildcard:/var/www/wildcard:ro
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s